name: Perps
ecosystem: fuel
networks:
  - id: 9889
    start_block: 0
    contracts:
      - name: AccountBalance
        address:
          - 0xc17dd80692a8987fb3d7b310061aaa27c1b9a12cd5d2dfc9e800d7bb01b54cf4
        abi_file_path: ./abis/account-balance.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: OwedRealizedPnlChangeEvent
          - name: AccountBalanceChangeEvent
      - name: PerpMarket
        address:
          - 0xc17dd80692a8987fb3d7b310061aaa27c1b9a12cd5d2dfc9e800d7bb01b54cf4
        abi_file_path: ./abis/perp-market.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: TradeEvent
          - name: OrderEvent
          - name: MarketEvent
      - name: Vault
        address:
          - 0xc615234baccb2dc002b92a091872782869e99c602e4759181d6cf827840c4a36
        abi_file_path: ./abis/vault.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: CollateralChangeEvent
      
            
            
            

            
