name: Perps
ecosystem: fuel
networks:
  - id: 9889
    start_block: 0
    contracts:
      - name: AccountBalance
        address:
          - 0x7b45943ab1b22185113b11e6b98bd128fdd416001274f6910866cb6ff644b246
        abi_file_path: ./abis/account-balance.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: OwedRealizedPnlChangeEvent
          - name: AccountBalanceChangeEvent
      - name: PerpMarket
        address:
          - 0x7b45943ab1b22185113b11e6b98bd128fdd416001274f6910866cb6ff644b246
        abi_file_path: ./abis/perp-market.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: TradeEvent
          - name: OrderEvent
          - name: MarketEvent
      - name: Vault
        address:
          - 0x104e908267fea156a8716b4fc4d238e71fb30a2566f26e71370d54bc5e1dfc6d
        abi_file_path: ./abis/vault.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: CollateralChangeEvent
      
            
            
            

            
