name: Perps
ecosystem: fuel
networks:
  - id: 9889
    start_block: 0
    contracts:
      - name: AccountBalance
        address:
          - 0x812aa6cb0828d3d1b069d0e2c1e4eab49c62841dc9eb71043ac71105c382e3b6
        abi_file_path: ./abis/account-balance.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: OwedRealizedPnlChangeEvent
          - name: AccountBalanceChangeEvent
      - name: PerpMarket
        address:
          - 0x812aa6cb0828d3d1b069d0e2c1e4eab49c62841dc9eb71043ac71105c382e3b6
        abi_file_path: ./abis/perp-market.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: TradeEvent
          - name: OrderEvent
          - name: MarketEvent
      - name: Vault
        address:
          - 0x996c3cb59e0ec48ccc1b3053debf165e778c4127b24fe90432d63deca772d07e
        abi_file_path: ./abis/vault.json
        handler: ./src/PerpsHandlers.ts
        events:
          - name: CollateralChangeEvent
      
            
            
            

            
