name: OrderBook
ecosystem: fuel
networks:
  - id: 9889
    start_block: 0
    contracts:
      - name: Account
        address:
          - 0xefad74ba7f8d09f5841c330a1199dc6bc7aef7712aa8344b35a7b984d5c9d7af
        abi_file_path: ./abis/account-balance.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: OwedRealizedPnlChangeEvent
          - name: AccountBalanceChangeEvent
            
            
            

            
